baseURL = 'https://weberi.github.io/jordanhorses'
languageCode = 'en-us'
title = 'Jordan Horses'
theme = 'ananke'

defaultContentLanguage = "en"
enableRobotsTXT = false


[params]
custom_css = ["custom.css"]
mainSections = ["options", "team", "horses", "camplife", "contact"]
background_color_class = "bg-yellow"
cover_dimming_class = "bg-gold-80"
featured_image_class = "cover bg-top"
text_color = "dark-gray"

body_classes = "avenir bg-light-silver"
post_content_classes = "avenir bg-light-silver"


read_more_copy = "Discover..."

[menu]
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "Options"
  url = "/options/"
  weight = 2

  [[menu.main]]
  name = "Team"
  url = "/Team/"
  weight = 3

  [[menu.main]]
  name = "Horses"
  url = "/horses/"
  weight = 4

  [[menu.main]]
  name = "Camplife"
  url = "/camplife/"
  weight = 5


  [[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 6


[pagination]
pagerSize = 12 





[params.ananke.social.follow]
networks = [
  "facebook",
  "instagram",
  "tripadvisor",
  "whatsapp", 
  "email"
]

[params.ananke.social.share]
networks = [
]

[params.ananke.social.facebook]
username = "share/165JjGguuL" 
# profilelink = "https://www.facebook.com/share/165JjGguuL/"

[params.ananke.social.instagram]
username = "fdoulmohammad86" 
# profilelink = "https://www.instagram.com/fdoulmohammad86/"

[params.ananke.social.networks.tripadvisor]
slug = "tripadvisor"
label = "Tripadvisor"
color = "#0645ad"
profile = "https://www.tripadvisor.com/Attraction_Review-g318895-d24150955-Reviews-Petra_Horse_Ride_Adventure-Petra_Wadi_Musa_Ma_an_Governorate.html?fbclid=PAY2xjawIlh2NleHRuA2FlbQIxMAABpkECojVzE-Rw1z2UWrjTNrxhyZh6W6Xiy2M_xq4yBTmk6vUEXrmi0YAhWQ_aem_jGIXmq2-G2ystl5fXSDMRg"
icon = "tripadvisor"

[params.ananke.social.networks.whatsapp]
slug = "whatsapp"
label = "Whatsapp"
color = "#0645ad"
profile = "https://wa.me/962772590240"
icon = "whatsapp"

[params.ananke.social.networks.email]
username = "fdoulmohammad86" 
slug = "email"
label = "Email"
share  = "mailto:fdoulmohammad86@gmail.com"
profile = "mailto:fdoulmohammad86@gmail.com?subject=Inquiry about Petra Tours"
icon = "envelope"




# 